In [ ]:
import requests
from bs4 import BeautifulSoup

In [ ]:
url='https://search.naver.com/search.naver?where=news&ie=utf8&sm=nws_hty&query=%EC%BD%94%EB%A1%9C%EB%82%98'

resp=requests.get(url)
resp

<Response [200]> 
- 응답코드: 클라이언트가 서버에 정보 요청을 했을 떄, 정보제공 여부에 대한 신호
- 응답코드: 웹페이지 정보 획득 성공 여부
- 200: 성공
- 404: 실패
- 응답코드는 1xx, 2xx, 3xx, 4xx, 5xx 등 많음
- 웹페이지 제작자가 실제 응답코드와 실패사유를 일치시켜놓지 않는 경우가 있음
- 200(성공), 404(실패) 이정도면 알고 실패시 메뉴얼보고 여러개 시도해보기

In [ ]:
html=resp.content
# html에 resp의 html을 담음

- resp.text : 문자열 형식 -> 사람친화적
- resp.content : 바이너리 형식 -> 기계친화적
- 한글의 경우 text로 하면 디코딩할때 깨질 수도 있음

In [ ]:
soup=BeautifulSoup(html, 'lxml')
# BeautifulSoup 형태로 변환, 파싱(Parsing)방법: lxml / lxml은 파싱 프로그램이름으로 가장 효율적이라고 알려져 있음
# html타입을 pyhton에서 다루기 위해 변경해주는 작업

tags=soup.select('a.news_tit')
# find, find_all보다 효율적인 함수. select를 쓰자
# . 은 클래스 " "은 하위태그

# ul class='a b c'
# select(ul.a.b.c) -> 불러오는 방법

# 클래스가 news_area인 div 태그 안에 있는 a 태그

type(tags), len(tags)
# 길이확인을 해서 본래 가져오가자 한것들의 개수와 일치하는지 확인

(list, 10)

In [ ]:
tags_rel=soup.select('div.tit')
len(tags_rel)

10

In [ ]:
url='https://search.naver.com/search.naver?where=news&ie=utf8&sm=nws_hty&query=%EC%BD%94%EB%A1%9C%EB%82%98'
resp=requests.get(url)
html=resp.content
soup = BeautifulSoup(resp.content, 'lxml')
a_tags=soup.select('a.news_tit')

for a_tag in a_tags:
    print(a_tag.text)

for a_tag in a_tags:
    print(a_tag['title'])

for a_tag in a_tags:
    print(a_tag['href'])

코로나19에 중단 됐던 김포~오사카·타이페이 30일 운항 재개
코로나 확산세… 신규확진 3만7321명, 전주보다 1만여명 증가
코로나19로 반려동물 용품 수출입 급증…역대 최대 규모
코로나 신규확진 3만7321명…"토요일 기준 6주만 3만명 넘겨"
코로나19 29일 3만7321명 확진… 31명 사망
“코로나 반등 조짐”…한 달여 만에 확진자 3만 명대로 ‘최다’
중대본 "신규 확진 3만 5천 명대…코로나19 유행 반등 조짐"
식약처, 모더나 두번째 코로나19 2가 백신 사전검토 착수
코로나 재유행 앞두고 '환기' 강조…"하루 3번, 매회 10분 이상"
교정시설 코로나 신규확진 50명…재유행 대비 현장점검
코로나19에 중단 됐던 김포~오사카·타이페이 30일 운항 재개
코로나 확산세… 신규확진 3만7321명, 전주보다 1만여명 증가
코로나19로 반려동물 용품 수출입 급증…역대 최대 규모
코로나 신규확진 3만7321명…"토요일 기준 6주만 3만명 넘겨"
코로나19 29일 3만7321명 확진… 31명 사망
“코로나 반등 조짐”…한 달여 만에 확진자 3만 명대로 ‘최다’
중대본 "신규 확진 3만 5천 명대…코로나19 유행 반등 조짐"
식약처, 모더나 두번째 코로나19 2가 백신 사전검토 착수
코로나 재유행 앞두고 '환기' 강조…"하루 3번, 매회 10분 이상"
교정시설 코로나 신규확진 50명…재유행 대비 현장점검
http://www.newsis.com/view/?id=NISX20221028_0002065865&cID=13001&pID=13000
https://biz.chosun.com/topics/topics_social/2022/10/29/5OYMEZEEYNDBXGBLMTTUODPDYY/?utm_source=naver&utm_medium=original&utm_campaign=biz
https://www.nocutnews.co.kr/news/5840321
http://news.mt.co.kr/mtview.php?no=2022102910403348645
http://www.fnnews.com/news/202210291001252104
https://www.donga.com/news/article/all/20221028/116200871/1
https://biz.sbs.co.kr/article_hub/20000086722?division=NAVER
https://www.yna.co.kr/view/AKR20221028121600017?input=1195m
https://biz.sbs.co.kr/article_hub/20000086798?division=NAVER
http://www.newsis.com/view/?id=NISX20221028_0002065171&cID=10201&pID=10200

In [ ]:
url='https://search.naver.com/search.naver?where=news&ie=utf8&sm=nws_hty&query=%EC%BD%94%EB%A1%9C%EB%82%98'
resp=requests.get(url)
html=resp.content
soup = BeautifulSoup(resp.content, 'lxml')
a_tags=soup.select('a.news_tit')

news_info={
    'title' : [],
    'url' : []
}

for a_tag in a_tags:
    news_info['title'].append(a_tag['title'])
    news_info['url'].append(a_tag['href'])

news_info

{'title': ['코로나19에 중단 됐던 김포~오사카·타이페이 30일 운항 재개',
  '코로나 확산세… 신규확진 3만7321명, 전주보다 1만여명 증가',
  '코로나19로 반려동물 용품 수출입 급증…역대 최대 규모',
  '코로나 신규확진 3만7321명…"토요일 기준 6주만 3만명 넘겨"',
  '코로나19 29일 3만7321명 확진… 31명 사망',
  '“코로나 반등 조짐”…한 달여 만에 확진자 3만 명대로 ‘최다’',
  '중대본 "신규 확진 3만 5천 명대…코로나19 유행 반등 조짐"',
  '식약처, 모더나 두번째 코로나19 2가 백신 사전검토 착수',
  '코로나 재유행 앞두고 \'환기\' 강조…"하루 3번, 매회 10분 이상"',
  '교정시설 코로나 신규확진 50명…재유행 대비 현장점검'],
 'url': ['http://www.newsis.com/view/?id=NISX20221028_0002065865&cID=13001&pID=13000',
  'https://biz.chosun.com/topics/topics_social/2022/10/29/5OYMEZEEYNDBXGBLMTTUODPDYY/?utm_source=naver&utm_medium=original&utm_campaign=biz',
  'https://www.nocutnews.co.kr/news/5840321',
  'http://news.mt.co.kr/mtview.php?no=2022102910403348645',
  'http://www.fnnews.com/news/202210291001252104',
  'https://www.donga.com/news/article/all/20221028/116200871/1',
  'https://biz.sbs.co.kr/article_hub/20000086722?division=NAVER',
  'https://www.yna.co.kr/view/AKR20221028121600017?input=1195m',
  'https://biz.sbs.co.kr/article_hub/20000086798?division=NAVER',
  'http://www.newsis.com/view/?id=NISX20221028_0002065171&cID=10201&pID=10200']}

In [ ]:
import pandas as pd

df_news=pd.DataFrame(news_info)
df_news.to_csv('뉴스정보.csv',encoding='utf-8-sig', index=False)
# index=False 인덱스로된 행을 저장하지 않겠다

In [ ]:
df_news=pd.read_csv('뉴스정보.csv')
df_news

,title,url
0,오늘부터 18∼59세도 코로나 개량백신 사전예약…3가지 중 택1,https://www.yna.co.kr/view/AKR2022102613760053...
1,코로나19 이후 경제력·학력 따른 건강 불평등 악화,http://www.newsis.com/view/?id=NISX20221027_00...
2,"신용보증기금, 코로나19 피해 기업에 5432억원 P-CBO 발행",https://www.hankyung.com/economy/article/20221...
3,"""코로나 때문에 간호사 약 59% 휴게시간 보장 못받아""",http://www.womennews.co.kr/news/articleView.ht...
4,'코로나 백신 이상반응' 누적 48만건…152건 추가 보상,http://www.newsis.com/view/?id=NISX20221027_00...
5,"코로나 개량 백신, 성인 전체로 확대… 오늘부터 예약 가능",https://www.donga.com/news/article/all/2022102...
6,"""코로나19 대응 부실로 80대 환자 사망""…요양병원 배상 책임",https://www.yna.co.kr/view/AKR2022102615750005...
7,동절기 코로나 백신 추가접종 ‘모든 성인’ 확대…2가백신 활용,https://biz.chosun.com/topics/topics_social/20...
8,코로나 일일 통계 발표 다음주부터 중단…홈페이지만 공개,https://www.joongang.co.kr/article/25112353
9,"코로나 동절기 접종 27일부터 예약…""모든 성인이 대상""",http://www.newsis.com/view/?id=NISX20221026_00...

In [ ]:
url='https://search.naver.com/search.naver?where=news&ie=utf8&sm=nws_hty&query=%EC%BD%94%EB%A1%9C%EB%82%98'
resp=requests.get(url)
html=resp.content
soup = BeautifulSoup(resp.content, 'lxml')

tags_rel=soup.select('div.tit')

for i in tags_rel:
    print(i.text)

코로나19
코로나 증상
코로나 생활지원금
코로나 지원금
코로나 검사
코로나 격리
코로나 확진자 격리
코로나 격리기간
코로나 재감염
코로나 변이

기사제목 100개 가져오기

In [ ]:
dict={'title' : [],
      'url' : []
      }

for i in range(1,92,10):
    url='https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%BD%94%EB%A1%9C%EB%82%98&sort=0&photo=0&field=0&pd=0&ds=&de=&cluster_rank=50&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:all,a:all&start={}'.format(i)
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')
    a_tags=soup.select('a.news_tit')

    for a_tag in a_tags:
        dict['title'].append(a_tag['title'])
        dict['url'].append(a_tag['href'])

In [ ]:
import pandas as pd
df=pd.DataFrame(dict)

df

,title,url
0,오늘부터 18∼59세도 코로나 개량백신 사전예약…3가지 중 택1,https://www.yna.co.kr/view/AKR2022102613760053...
1,코로나19 이후 경제력·학력 따른 건강 불평등 악화,http://www.newsis.com/view/?id=NISX20221027_00...
2,코로나19 백신 피해보상 2만1502건… 사망 인과성 인정 11건,http://moneys.mt.co.kr/news/mwView.php?no=2022...
3,"코로나 개량 백신, 성인 전체로 확대… 오늘부터 예약 가능",https://www.donga.com/news/article/all/2022102...
4,동절기 코로나 백신 추가접종 ‘모든 성인’ 확대…2가백신 활용,https://biz.chosun.com/topics/topics_social/20...
...,...,...
95,"[기업사회활동] 미래에셋생명, 포스트 코로나 맞아 참여형 언택트 봉사 나서",http://www.lawissue.co.kr/view.php?ud=20221024...
96,[그래픽]코로나19 확진자 지역별 현황(27일),https://www.news1.kr/photos/view/?5651188
97,광주 지역 코로나19 지표 점점 악화…겨울 재유행 우려,https://www.yna.co.kr/view/AKR2022102610030005...
98,"""바이든도 코로나 후유증 겪었나?"" ""주치의 아니라서…""",http://www.segye.com/content/html/2022/10/26/2...
99,코로나19 방역로봇,https://www.yna.co.kr/view/PYH2022102610250001...

In [ ]:
url='https://comic.naver.com/webtoon/weekday'
resp=requests.get(url)
html=resp.content
soup=BeautifulSoup(html, 'lxml')
tags_name=soup.select('a.title')
for name in tags_name:
    print(name.text)

참교육
뷰티풀 군바리
퀘스트지상주의
장씨세가 호위무사
윈드브레이커
팔이피플
퍼니게임
신화급 귀속 아이템을 손에 넣었다
소녀의 세계
버림받은 왕녀의 은밀한 침실
호랑신랑뎐
앵무살수
백수세끼
잔불의 기사
사이다걸
똑 닮은 딸
절대검감
꼬리잡기
히어로메이커
리턴 투 플레이어
북부 공작님을 유혹하겠습니다
물어보는 사이
도깨비 부른다
순정말고 순종
헬크래프트
더블클릭
결혼생활 그림일기
아, 쫌 참으세요 영주님!
또다시, 계약 부부
황제와의 하룻밤
기사님을 지켜줘
오빠집이 비어서
제왕: 빛과 그림자
불청객
꿈의 기업
파운더
이제야 연애
미니어처 생활백서
퇴근 후에 만나요
신군
아슈타르테
우산 없는 애
하루의 하루
레지나레나 - 용서받지 못한 그대에게
원작은 완결난 지 한참 됐습니다만
다시쓰는 연애사
굿바이 유교보이
그림자 신부
메리의 불타는 행복회로
오늘의 비너스
입술이 예쁜 남자
행운을 부탁해!
아마도
버그이터
최후의 금빛아이
백호랑
파견체
달로 만든 아이
루크 비셸 따라잡기
모스크바의 여명
나만의 고막남친
세번째 로망스
매지컬 급식:암살법사
경비실에서 안내방송 드립니다
지옥연애환담
악녀 18세 공략기
역주행!
모노마니아
사막에 핀 달
슈퍼스타 천대리
흔들리는 세계로부터
남주서치
결혼공략
디나운스
별을 쫓는 소년들
오로지 오로라
김부장
대학원 탈출일지
내가 키운 S급들
여신강림
마루는 강쥐
1을 줄게
멸망 이후의 세계
하루만 네가 되고 싶어
중증외상센터 : 골든 아워
용사가 돌아왔다
삼국지톡
헬58
악몽의 형상
천마는 평범하게 살 수 없다
집이 없어
랜덤채팅의 그녀!
하북팽가 막내아들
시체기사 군터
호랑이 들어와요
웅크
초인의 게임
사표내고 이계에서 힐링합니다
올가미
원주민 공포만화
윌유메리미
100
덴큐
나타나주세요!
애옹식당
헥토파스칼
용왕님의 셰프가 되었습니다
늑대처럼 홀로
왕게임
견우와 선녀
택배 왔습니다
로잘린 보가트
에이머
빅맨
은주의 방 2~3부
빌런투킬
사공은주
플레이, 플리
아이즈
또 다른 사랑
내남친 킹카만들기
나의 플랏메이트
제로게임
벽간소음
여우자매
풋내기들
열녀박씨 계약결혼뎐
한입만!
1331
쿠쿠쿠쿠
붉은 이정표
필리아로제 - 가시왕관의 예언
AI 유하
짝사랑의 마침표
주인님을 잡아먹는 방법
테러사이트
이 결혼, 새로고침
나는 어디에나 있다
이븐 모어
그녀석 정복기
그 남주와 이별하는 방법
마침내 사랑이에요 마왕님!
NG불가
태시트
대신 심부름을 해다오
원수가 나를 유혹할 때
교환학생
급식러너
찐:종합게임동아리
달이 사라진 밤
위아더좀비
잿빛오름
너의 순정, 나의 순정
하나in세인
마녀이야기
내 남편과 결혼해줘
전지적 독자 시점
헬퍼 2 : 킬베로스
먹는 인생
격기3반
조조코믹스
무림서부
일렉시드
비즈니스 여친
여고생 드래곤
나쁜사람
튜토리얼 탑의 고인물
내가 죽기로 결심한 것은
이십팔세기 광팬
급식아빠
연놈
빌드업
마른 가지에 바람처럼
지금 우리 연구소는
칼에 취한 밤을 걷다
미래의 골동품 가게
사상최강
기묘한 만화
안녕, 나의 수집
쓰레기는 쓰레기통에!
고삼무쌍
세상은 돈과 권력
베스트 프렌드
운명을 보는 회사원
하얀 사자의 비밀 신부
물고기로 살아남기
언덕 위의 제임스
판타지 여동생!
아도나이
그 남자의 은밀한 하루
칼부림
수요웹툰의 나강림
사내고충처리반
마녀와 용의 신혼일기
얼굴천재
헤어지면 죽음
선배는 나빠요!
영웅&마왕&악당
가짜 동맹
로어 올림푸스
괴물공작의 딸
반귀
주부 육성중
인과관계
좀간
두 번 사는 프로듀서
내겐 너무 소란한 결혼
범이올시다!
밀행
홀리데이
메모리얼
옆집남자 친구
그림자의 밤
잿빛도 색이다
나의 계절
재생존경쟁
안미운 우리들
하렘의 남자들
사랑과 평강의 온달!
구사일생 로맨스
멸종위기종인간
어느 백작 영애의 이중생활
클로닝
반짝반짝 작은 눈
이별학
무용과 남학생
혁명 뒤 공주는
하지만 너는 2D잖아
낙원의 이론
해귀
프로듀스 온리원
수호하는 너에게
산의 시간
오직, 밝은 미래
이 짝사랑은 억울하다!
필생기
우리 은하
아이돌의 비밀 스터디
나노마신
연애혁명
2022 몰래보는 로맨스
독립일기
남편을 죽여줘요
천마육성
이상한 변호사 우영우
현실퀘스트
호랑신랑뎐
나 혼자 네크로맨서
무사만리행
회귀한 천재 헌터의 슬기로운 청소생활
버려진 나의 최애를 위하여
재벌집 막내아들
노답소녀
별을 삼킨 너에게
쿠베라
누나! 나 무서워
뮤즈 온 유명
던전 씹어먹는 아티팩트
꽃만 키우는데 너무강함
트롤트랩
최강전설 강해효
국세청 망나니
황제사냥
완벽한 결혼의 정석
순정빌런
규격 외 혈통 천재
오빠세끼
마왕까지 한 걸음
만능잡캐
네가 죽기를 바랄 때가 있었다
죄송한데 주인공이세요?
관계중독
만물의 영장
순수한 동거생활
선남친 후연애
위대한 겸상
개와 사람의 시간
킬더킹
아인슈페너
소녀180
가족같은 XX
베니루 BAENIRU
나의 불편한 상사
천재의 게임방송
두 번째 딸로 태어났습니다
온에어
1학년 9반
부캐인생
마녀의 심판은 꽃이 된다
그 황제가 시곗바늘을 되돌린 사연
THE 런웨이
달의 요람
갓트
환상연가
진짜 진짜 이혼해
오, 친애하는 숙적
가상&RPG
황궁에 핀 꽃은, 미쳤다
해시의 신루
온새미로
방과후 레시피
따개비
이계 무슨 황비
침묵의 밤
돌아온 여기사
아빠같은 남자
배트맨: 웨인 패밀리 어드벤처
베어케어
카루나
로맨틱 태평수산
시에라
자취방 신선들
연애의 발견
나쁜 마법사의 꿈
온실 속 화초
혼모노트
보물과 괴물의 도시
널 사랑하는 죽은 형
유월의 소한
권리행사자
사랑하는 여배우들
모어 라이프
게임 최강 트롤러
비서 일탈
외모지상주의
대학원 탈출일지
광마회귀
갓 오브 하이스쿨
나 혼자 만렙 뉴비
어쩌다보니 천생연분
역대급 영지 설계사
데드퀸
개를 낳았다
세기말 풋사과 보습학원
삼국지톡
사신
상남자
낙향문사전
소름일기
언니, 이번 생엔 내가 왕비야
지옥 키우기
더 게이머
서울역 드루이드
웅크
히어로 킬러
말년용사
언다잉
그들이 사귀는 세상
A.I. 닥터
온리호프
그렇고 그런 바람에
여자를 사귀고 싶다
플레이어
성스러운 그대 이르시길
푸쉬오프
이터널 포스
선을 넘은 연애
문제적 왕자님
너의 미소가 함정
절대복종
후덜덜덜 남극전자
킬 더 드래곤
메소드 연기법
그 기사가 레이디로 사는 법
스포
미드우트
멜빈이 그들에게 남긴 것
여름여자 하보이
상위1%
지니오패스
이게 아닌데
쿠쿠쿠쿠
스토커의 하루
거래
악마라고 불러다오
네버엔딩달링
로또 황녀님
1초
트럼프
아찔한 전남편
달이 없는 나라
솔트앤페퍼
몽홀
비밀친구
인피니티
백년게임
재앙의 날
드래곤의 심장을 가지고 있습니다
태권보이
짝사랑 마들렌
너의 키스씬
별빛 커튼콜
천상의 주인
리트리츠
여름의 너에게
합법해적 파르페
팬시X팬시
서울시 천사주의
너에게 입덕중
스치면 인연 스며들면 사랑
99강화나무몽둥이
호랑이형님
2022 몰래보는 로맨스
취사병 전설이 되다
먹는 인생
조조코믹스
프리드로우
여고생 드래곤
망나니 소교주로 환생했다
이십팔세기 광팬
은탄
악몽의 형상
아홉수 우리들
스터디그룹
청춘 블라썸
나이트런
반드시 해피엔딩
간첩 18세
작전명 순정
윌유메리미
나태 공자, 노력 천재 되다
세레나
어글리후드
소공녀 민트
나를 바꿔줘
존잘주의
미나 이퀄
탑코너
물위의 우리
아사
남편 먹는 여자
용두사망 소설 속의 악녀가 되었다
태백 : 튜토리얼 맨
좀비 파이트
디펜스 게임의 폭군이 되었다
홍시는 날 좋아해!
용사참수인
이계진입 리로디드
대충 캠퍼스로맨스임
같은 학교 친구
엑스애쉬
팬인데 왜요
남편을 만렙으로 키우려 합니다
폭군 남편과 이혼하겠습니다
지옥급식
묘령의 황자
공유몽
완벽한 부부는 없다
메트로헌터
최면학교
광해의 연인
마법사가 죽음을 맞이하는 방법
최강부캐
전생연분
키스 식스 센스
다비, 아찔하게 흐르는
은둔코인
소년 검사
복수를 위한 결혼동맹
적월의 나라
왕년엔 용사님
중매쟁이 아가 황녀님
모두 너였다
청춘일지
배달의 신
키스의 여왕
7FATES: CHAKHO
도사 가온
스트릿 워크아웃
아가사
밤을 깨우는 마법
숨겨진 성녀
보고 있지?
좋아해 아니 싫어해
보듬보듬
이건 그냥 연애 이야기
아침을 지나 밤으로
실버 쥬얼
싸움독학
독립일기
입학용병
약한영웅
사형소년
이번 생도 잘 부탁해
수희0(tngmlek0)
자매전쟁
별이삼샵
살아남은 로맨스
천하제일인
일타강사 백사부
시월드가 내게 집착한다
안녕, 나의 수집
칼끝에 입술
곱게 키웠더니, 짐승
분신으로 자동사냥
가비지타임
판사 이한영
노량진 공격대
무서운게 딱좋아!
헬스던전
내일
약빨이 신선함
아카데미에 위장취업당했다
오로지 너를 이기고 싶어
마법스크롤 상인 지오
어느날 갑자기 서울은
경자 전성시대
폰투스 : 극야2
합격시켜주세용
장풍전
위닝샷!
동생친구
고백 취소도 되나?
손 안의 안단테
백설을 위하여
평행도시
랑데뷰
천치전능
몸이 바뀌는 사정
생존로그
후궁 스캔들
장미같은 소리
결혼까지 망상했어!
키미앤조이
위험한 남편을 길들이는 법
108명의 그녀들
소녀재판
마왕의 고백
여우애담
홍 의관의 은밀한 비밀
나의 작은 서점
데빌샷
킬링킬러
돌&아이
DARK MOON: 달의 제단
전설의 화석
내곁엔 없을까
생존고백
하렘에서 살아남기
보스의 노골적 취향
블러드 리벤저
철수와 영희 이야기
마섹남 - 마술하는 섹시한 남자
보통아이
6월의 라벤더
패션쇼
샤인 스타
마도
사람은 고쳐 쓰는 게 아니야!
조선여우스캔들
밀실 마피아 게임
아마도, 굿모닝
어떤소란
거래하실래요?
독신마법사 기숙아파트
구해줘, 호구!

In [ ]:
list=['mon','tue','wed','tur','fri','sat','sun']

for day in list:
    
    url='https://comic.naver.com/webtoon/weekdayList?week={}'.format(day)
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')
    tags_name=soup.select('dl dt a')
    
    name=[]
    for cartoon in tags_name:
        name.append(cartoon.text)
    print("{} : {}".format(day,name))
    print("{} 웹툰 개수 : {}".format(day,len(name)))

# 페이지 상단의 추천웹툰도 가져와짐

#dl dt a 가 제목인데

#하단 추천웹툰에 떠있는거
# <a href="/webtoon/list?titleId=785749&amp;weekday=mon" title="슈퍼스타 천대리">슈퍼스타 천대리</a>

# 상단 전체웹툰에 떠있는거(dl dt a의 하위태그에 속해있음)
# <strong title="슈퍼스타 천대리">슈퍼스타 천대리</strong>

mon : ['슈퍼스타 천대리\n', '꼬리잡기\n', '헬크래프트\n', '참교육', '뷰티풀 군바리', '퀘스트지상주의', '장씨세가 호위...', '윈드브레이커', '팔이피플', '퍼니게임', '신화급 귀속 ...', '소녀의 세계', '버림받은 왕녀...', '호랑신랑뎐', '앵무살수', '백수세끼', '잔불의 기사', '사이다걸', '똑 닮은 딸', '절대검감', '꼬리잡기', '히어로메이커', '리턴 투 플레...', '북부 공작님을...', '물어보는 사이', '도깨비 부른다', '순정말고 순종', '헬크래프트', '더블클릭', '결혼생활 그림...', '아, 쫌 참으...', '또다시, 계약...', '황제와의 하룻밤', '기사님을 지켜줘', '오빠집이 비어서', '제왕: 빛과 ...', '불청객', '꿈의 기업', '파운더', '이제야 연애', '미니어처 생활...', '퇴근 후에 만...', '신군', '아슈타르테', '우산 없는 애', '하루의 하루', '레지나레나 -...', '원작은 완결난...', '다시쓰는 연애사', '굿바이 유교보이', '그림자 신부', '메리의 불타는...', '오늘의 비너스', '입술이 예쁜 ...', '행운을 부탁해!', '아마도', '버그이터', '최후의 금빛아이', '백호랑', '파견체', '달로 만든 아이', '루크 비셸 따...', '모스크바의 여명', '나만의 고막남친', '세번째 로망스', '매지컬 급식:...', '경비실에서 안...', '지옥연애환담', '악녀 18세 ...', '역주행!', '모노마니아', '사막에 핀 달', '슈퍼스타 천대리', '흔들리는 세계...', '남주서치', '결혼공략', '디나운스', '별을 쫓는 소...', '오로지 오로라']
mon 웹툰 개수 : 79
tue : ['마루는 강쥐\n', '용왕님의 셰프가 되었습니다\n', '호랑이 들어와요\n', '김부장', '대학원 탈출일지', '내가 키운 S...', '여신강림', '마루는 강쥐', '1을 줄게', '멸망 이후의 ...', '하루만 네가 ...', '중증외상센터 ...', '용사가 돌아왔다', '삼국지톡', '헬58', '악몽의 형상', '천마는 평범하...', '집이 없어', '랜덤채팅의 그...', '하북팽가 막내...', '시체기사 군터', '호랑이 들어와요', '웅크', '초인의 게임', '사표내고 이계...', '올가미', '원주민 공포만화', '윌유메리미', '100', '덴큐', '나타나주세요!', '애옹식당', '헥토파스칼', '용왕님의 셰프...', '늑대처럼 홀로', '왕게임', '견우와 선녀', '택배 왔습니다', '로잘린 보가트', '에이머', '빅맨', '은주의 방 2...', '빌런투킬', '사공은주', '플레이, 플리', '아이즈', '또 다른 사랑', '내남친 킹카만...', '나의 플랏메이트', '제로게임', '벽간소음', '여우자매', '풋내기들', '열녀박씨 계약...', '한입만!', '1331', '쿠쿠쿠쿠', '붉은 이정표', '필리아로제 -...', 'AI 유하', '짝사랑의 마침표', '주인님을 잡아...', '테러사이트', '이 결혼, 새...', '나는 어디에나...', '이븐 모어', '그녀석 정복기', '그 남주와 이...', '마침내 사랑이...', 'NG불가', '태시트', '대신 심부름을...', '원수가 나를 ...', '교환학생', '급식러너', '찐:종합게임동...', '달이 사라진 밤', '위아더좀비', '잿빛오름', '너의 순정, ...', '하나in세인', '마녀이야기']
tue 웹툰 개수 : 82
wed : ['전지적 독자 시점\n', '홀리데이\n', '판타지 여동생!\n', '내 남편과 결...', '전지적 독자 ...', '헬퍼 2 : ...', '먹는 인생', '격기3반', '조조코믹스', '무림서부', '일렉시드', '비즈니스 여친', '여고생 드래곤', '나쁜사람', '튜토리얼 탑의...', '내가 죽기로 ...', '이십팔세기 광팬', '급식아빠', '연놈', '빌드업', '마른 가지에 ...', '지금 우리 연...', '칼에 취한 밤...', '미래의 골동품...', '사상최강', '기묘한 만화', '안녕, 나의 ...', '쓰레기는 쓰레...', '고삼무쌍', '세상은 돈과 ...', '베스트 프렌드', '운명을 보는 ...', '하얀 사자의 ...', '물고기로 살아...', '언덕 위의 제...', '판타지 여동생!', '아도나이', '그 남자의 은...', '칼부림', '수요웹툰의 나...', '사내고충처리반', '마녀와 용의 ...', '얼굴천재', '헤어지면 죽음', '선배는 나빠요!', '영웅&...', '가짜 동맹', '로어 올림푸스', '괴물공작의 딸', '반귀', '주부 육성중', '인과관계', '좀간', '두 번 사는 ...', '내겐 너무 소...', '범이올시다!', '밀행', '홀리데이', '메모리얼', '옆집남자 친구', '그림자의 밤', '잿빛도 색이다', '나의 계절', '재생존경쟁', '안미운 우리들', '하렘의 남자들', '사랑과 평강의...', '구사일생 로맨스', '멸종위기종인간', '어느 백작 영...', '클로닝', '반짝반짝 작은...', '이별학', '무용과 남학생', '혁명 뒤 공주는', '하지만 너는 ...', '낙원의 이론', '해귀', '프로듀스 온리원', '수호하는 너에게', '산의 시간', '오직, 밝은 ...', '이 짝사랑은 ...', '필생기', '우리 은하', '아이돌의 비밀...']
wed 웹툰 개수 : 86
tur : ['온실 속 화초\n', '쿠베라\n', '권리행사자\n', '나노마신', '연애혁명', '2022 몰래...', '독립일기', '남편을 죽여줘요', '천마육성', '이상한 변호사...', '현실퀘스트', '호랑신랑뎐', '나 혼자 네크...', '무사만리행', '회귀한 천재 ...', '버려진 나의 ...', '재벌집 막내아들', '노답소녀', '별을 삼킨 너...', '쿠베라', '누나! 나 무...', '뮤즈 온 유명', '던전 씹어먹는...', '꽃만 키우는데...', '트롤트랩', '최강전설 강해효', '국세청 망나니', '황제사냥', '완벽한 결혼의...', '순정빌런', '규격 외 혈통...', '오빠세끼', '마왕까지 한 ...', '만능잡캐', '네가 죽기를 ...', '죄송한데 주인...', '관계중독', '만물의 영장', '순수한 동거생활', '선남친 후연애', '위대한 겸상', '개와 사람의 ...', '킬더킹', '아인슈페너', '소녀180', '가족같은 XX', '베니루 BAE...', '나의 불편한 ...', '천재의 게임방송', '두 번째 딸로...', '온에어', '1학년 9반', '부캐인생', '마녀의 심판은...', '그 황제가 시...', 'THE 런웨이', '달의 요람', '갓트', '환상연가', '진짜 진짜 이...', '오, 친애하는...', '가상&...', '황궁에 핀 꽃...', '해시의 신루', '온새미로', '방과후 레시피', '따개비', '이계 무슨 황비', '침묵의 밤', '돌아온 여기사', '아빠같은 남자', '배트맨: 웨인...', '베어케어', '카루나', '로맨틱 태평수산', '시에라', '자취방 신선들', '연애의 발견', '나쁜 마법사의...', '온실 속 화초', '혼모노트', '보물과 괴물의...', '널 사랑하는 ...', '유월의 소한', '권리행사자', '사랑하는 여배...', '모어 라이프', '게임 최강 트...', '비서 일탈']
tur 웹툰 개수 : 89
fri : ['짝사랑 마들렌\n', '여자를 사귀고 싶다\n', '상위1%\n', '외모지상주의', '대학원 탈출일지', '광마회귀', '갓 오브 하이...', '나 혼자 만렙...', '어쩌다보니 천...', '역대급 영지 ...', '데드퀸', '개를 낳았다', '세기말 풋사과...', '삼국지톡', '사신', '상남자', '낙향문사전', '소름일기', '언니, 이번 ...', '지옥 키우기', '더 게이머', '서울역 드루이드', '웅크', '히어로 킬러', '말년용사', '언다잉', 'A.I. 닥터', '온리호프', '그렇고 그런 ...', '여자를 사귀고...', '플레이어', '성스러운 그대...', '푸쉬오프', '이터널 포스', '선을 넘은 연애', '문제적 왕자님', '너의 미소가 ...', '절대복종', '후덜덜덜 남극...', '킬 더 드래곤', '메소드 연기법', '그 기사가 레...', '스포', '미드우트', '멜빈이 그들에...', '여름여자 하보이', '상위1%', '지니오패스', '이게 아닌데', '쿠쿠쿠쿠', '스토커의 하루', '거래', '악마라고 불러...', '네버엔딩달링', '로또 황녀님', '1초', '트럼프', '아찔한 전남편', '달이 없는 나라', '솔트앤페퍼', '몽홀', '비밀친구', '인피니티', '백년게임', '재앙의 날', '드래곤의 심장...', '태권보이', '짝사랑 마들렌', '너의 키스씬', '별빛 커튼콜', '천상의 주인', '리트리츠', '여름의 너에게', '합법해적 파르페', '팬시X팬시', '서울시 천사주의', '너에게 입덕중', '스치면 인연 ...']
fri 웹툰 개수 : 78
sat : ['보듬보듬\n', '엑스애쉬\n', '먹는 인생\n', '99강화나무몽...', '호랑이형님', '2022 몰래...', '취사병 전설이...', '먹는 인생', '조조코믹스', '프리드로우', '여고생 드래곤', '망나니 소교주...', '이십팔세기 광팬', '은탄', '악몽의 형상', '아홉수 우리들', '스터디그룹', '청춘 블라썸', '나이트런', '반드시 해피엔딩', '간첩 18세', '작전명 순정', '윌유메리미', '나태 공자, ...', '세레나', '어글리후드', '소공녀 민트', '나를 바꿔줘', '존잘주의', '미나 이퀄', '탑코너', '물위의 우리', '아사', '남편 먹는 여자', '용두사망 소설...', '태백 : 튜토...', '좀비 파이트', '디펜스 게임의...', '홍시는 날 좋...', '용사참수인', '이계진입 리로...', '대충 캠퍼스로...', '같은 학교 친구', '엑스애쉬', '팬인데 왜요', '남편을 만렙으...', '폭군 남편과 ...', '지옥급식', '묘령의 황자', '공유몽', '완벽한 부부는...', '메트로헌터', '최면학교', '광해의 연인', '마법사가 죽음...', '최강부캐', '전생연분', '키스 식스 센스', '다비, 아찔하...', '은둔코인', '소년 검사', '복수를 위한 ...', '적월의 나라', '왕년엔 용사님', '중매쟁이 아가...', '모두 너였다', '청춘일지', '배달의 신', '키스의 여왕', '7FATES:...', '도사 가온', '스트릿 워크아웃', '아가사', '밤을 깨우는 ...', '숨겨진 성녀', '보고 있지?', '좋아해 아니 ...', '보듬보듬', '이건 그냥 연...', '아침을 지나 ...', '실버 쥬얼']
sat 웹툰 개수 : 81
sun : ['판사 이한영\n', '6월의 라벤더\n', '장미같은 소리\n', '싸움독학', '독립일기', '입학용병', '약한영웅', '사형소년', '이번 생도 잘...', '수희0(tng...', '자매전쟁', '별이삼샵', '살아남은 로맨스', '천하제일인', '일타강사 백사부', '시월드가 내게...', '안녕, 나의 ...', '칼끝에 입술', '곱게 키웠더니...', '분신으로 자동...', '가비지타임', '판사 이한영', '노량진 공격대', '무서운게 딱좋...', '헬스던전', '내일', '약빨이 신선함', '아카데미에 위...', '오로지 너를 ...', '마법스크롤 상...', '어느날 갑자기...', '경자 전성시대', '폰투스 : 극...', '합격시켜주세용', '장풍전', '위닝샷!', '동생친구', '고백 취소도 ...', '손 안의 안단테', '백설을 위하여', '평행도시', '랑데뷰', '천치전능', '몸이 바뀌는 ...', '생존로그', '후궁 스캔들', '장미같은 소리', '결혼까지 망상...', '키미앤조이', '위험한 남편을...', '108명의 그...', '소녀재판', '마왕의 고백', '여우애담', '홍 의관의 은...', '나의 작은 서점', '데빌샷', '킬링킬러', '돌&아이', 'DARK MO...', '전설의 화석', '내곁엔 없을까', '생존고백', '하렘에서 살아...', '보스의 노골적...', '블러드 리벤저', '철수와 영희 ...', '마섹남 - 마...', '보통아이', '6월의 라벤더', '패션쇼', '샤인 스타', '마도', '사람은 고쳐 ...', '조선여우스캔들', '밀실 마피아 ...', '아마도, 굿모닝', '어떤소란', '거래하실래요?', '독신마법사 기...', '구해줘, 호구!']
sun 웹툰 개수 : 81

In [ ]:
# 해결방법
# 상위 태그로 이동하면서 속성값으로 class 나 id 를 가지는 상위 태그까지 경로 넣어주기
list=['mon','tue','wed','tur','fri','sat','sun']

for day in list:
    
    url='https://comic.naver.com/webtoon/weekdayList?week={}'.format(day)
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')
    tags_name=soup.select('ul.img_list li dl dt a')
    
    name=[]
    for cartoon in tags_name:
        name.append(cartoon.text)
    print("{} : {}".format(day,name))
    print("{} 웹툰 개수 : {}".format(day,len(name)))

mon : ['참교육', '뷰티풀 군바리', '퀘스트지상주의', '장씨세가 호위...', '윈드브레이커', '팔이피플', '퍼니게임', '신화급 귀속 ...', '소녀의 세계', '버림받은 왕녀...', '호랑신랑뎐', '앵무살수', '백수세끼', '잔불의 기사', '사이다걸', '똑 닮은 딸', '절대검감', '꼬리잡기', '히어로메이커', '리턴 투 플레...', '북부 공작님을...', '물어보는 사이', '도깨비 부른다', '순정말고 순종', '헬크래프트', '더블클릭', '결혼생활 그림...', '아, 쫌 참으...', '또다시, 계약...', '황제와의 하룻밤', '기사님을 지켜줘', '오빠집이 비어서', '제왕: 빛과 ...', '불청객', '꿈의 기업', '파운더', '이제야 연애', '미니어처 생활...', '퇴근 후에 만...', '신군', '아슈타르테', '우산 없는 애', '하루의 하루', '레지나레나 -...', '원작은 완결난...', '다시쓰는 연애사', '굿바이 유교보이', '그림자 신부', '메리의 불타는...', '오늘의 비너스', '입술이 예쁜 ...', '행운을 부탁해!', '아마도', '버그이터', '최후의 금빛아이', '백호랑', '파견체', '달로 만든 아이', '루크 비셸 따...', '모스크바의 여명', '나만의 고막남친', '세번째 로망스', '매지컬 급식:...', '경비실에서 안...', '지옥연애환담', '악녀 18세 ...', '역주행!', '모노마니아', '사막에 핀 달', '슈퍼스타 천대리', '흔들리는 세계...', '남주서치', '결혼공략', '디나운스', '별을 쫓는 소...', '오로지 오로라']
mon 웹툰 개수 : 76
tue : ['김부장', '대학원 탈출일지', '내가 키운 S...', '여신강림', '마루는 강쥐', '1을 줄게', '멸망 이후의 ...', '하루만 네가 ...', '중증외상센터 ...', '용사가 돌아왔다', '삼국지톡', '헬58', '악몽의 형상', '천마는 평범하...', '집이 없어', '랜덤채팅의 그...', '하북팽가 막내...', '시체기사 군터', '호랑이 들어와요', '웅크', '초인의 게임', '사표내고 이계...', '올가미', '원주민 공포만화', '윌유메리미', '100', '덴큐', '나타나주세요!', '애옹식당', '헥토파스칼', '용왕님의 셰프...', '늑대처럼 홀로', '왕게임', '견우와 선녀', '택배 왔습니다', '로잘린 보가트', '에이머', '빅맨', '은주의 방 2...', '빌런투킬', '사공은주', '플레이, 플리', '아이즈', '또 다른 사랑', '내남친 킹카만...', '나의 플랏메이트', '제로게임', '벽간소음', '여우자매', '풋내기들', '열녀박씨 계약...', '한입만!', '1331', '쿠쿠쿠쿠', '붉은 이정표', '필리아로제 -...', 'AI 유하', '짝사랑의 마침표', '주인님을 잡아...', '테러사이트', '이 결혼, 새...', '나는 어디에나...', '이븐 모어', '그녀석 정복기', '그 남주와 이...', '마침내 사랑이...', 'NG불가', '태시트', '대신 심부름을...', '원수가 나를 ...', '교환학생', '급식러너', '찐:종합게임동...', '달이 사라진 밤', '위아더좀비', '잿빛오름', '너의 순정, ...', '하나in세인', '마녀이야기']
tue 웹툰 개수 : 79
wed : ['내 남편과 결...', '전지적 독자 ...', '헬퍼 2 : ...', '먹는 인생', '격기3반', '조조코믹스', '무림서부', '일렉시드', '비즈니스 여친', '여고생 드래곤', '나쁜사람', '튜토리얼 탑의...', '내가 죽기로 ...', '이십팔세기 광팬', '급식아빠', '연놈', '빌드업', '마른 가지에 ...', '지금 우리 연...', '칼에 취한 밤...', '미래의 골동품...', '사상최강', '기묘한 만화', '안녕, 나의 ...', '쓰레기는 쓰레...', '고삼무쌍', '세상은 돈과 ...', '베스트 프렌드', '운명을 보는 ...', '하얀 사자의 ...', '물고기로 살아...', '언덕 위의 제...', '판타지 여동생!', '아도나이', '그 남자의 은...', '칼부림', '수요웹툰의 나...', '사내고충처리반', '마녀와 용의 ...', '얼굴천재', '헤어지면 죽음', '선배는 나빠요!', '영웅&...', '가짜 동맹', '로어 올림푸스', '괴물공작의 딸', '반귀', '주부 육성중', '인과관계', '좀간', '두 번 사는 ...', '내겐 너무 소...', '범이올시다!', '밀행', '홀리데이', '메모리얼', '옆집남자 친구', '그림자의 밤', '잿빛도 색이다', '나의 계절', '재생존경쟁', '안미운 우리들', '하렘의 남자들', '사랑과 평강의...', '구사일생 로맨스', '멸종위기종인간', '어느 백작 영...', '클로닝', '반짝반짝 작은...', '이별학', '무용과 남학생', '혁명 뒤 공주는', '하지만 너는 ...', '낙원의 이론', '해귀', '프로듀스 온리원', '수호하는 너에게', '산의 시간', '오직, 밝은 ...', '이 짝사랑은 ...', '필생기', '우리 은하', '아이돌의 비밀...']
wed 웹툰 개수 : 83
tur : ['나노마신', '연애혁명', '2022 몰래...', '독립일기', '남편을 죽여줘요', '천마육성', '이상한 변호사...', '현실퀘스트', '호랑신랑뎐', '나 혼자 네크...', '무사만리행', '회귀한 천재 ...', '버려진 나의 ...', '재벌집 막내아들', '노답소녀', '별을 삼킨 너...', '쿠베라', '누나! 나 무...', '뮤즈 온 유명', '던전 씹어먹는...', '꽃만 키우는데...', '트롤트랩', '최강전설 강해효', '국세청 망나니', '황제사냥', '완벽한 결혼의...', '순정빌런', '규격 외 혈통...', '오빠세끼', '마왕까지 한 ...', '만능잡캐', '네가 죽기를 ...', '죄송한데 주인...', '관계중독', '만물의 영장', '순수한 동거생활', '선남친 후연애', '위대한 겸상', '개와 사람의 ...', '킬더킹', '아인슈페너', '소녀180', '가족같은 XX', '베니루 BAE...', '나의 불편한 ...', '천재의 게임방송', '두 번째 딸로...', '온에어', '1학년 9반', '부캐인생', '마녀의 심판은...', '그 황제가 시...', 'THE 런웨이', '달의 요람', '갓트', '환상연가', '진짜 진짜 이...', '오, 친애하는...', '가상&...', '황궁에 핀 꽃...', '해시의 신루', '온새미로', '방과후 레시피', '따개비', '이계 무슨 황비', '침묵의 밤', '돌아온 여기사', '아빠같은 남자', '배트맨: 웨인...', '베어케어', '카루나', '로맨틱 태평수산', '시에라', '자취방 신선들', '연애의 발견', '나쁜 마법사의...', '온실 속 화초', '혼모노트', '보물과 괴물의...', '널 사랑하는 ...', '유월의 소한', '권리행사자', '사랑하는 여배...', '모어 라이프', '게임 최강 트...', '비서 일탈']
tur 웹툰 개수 : 86
fri : ['외모지상주의', '대학원 탈출일지', '광마회귀', '갓 오브 하이...', '나 혼자 만렙...', '어쩌다보니 천...', '역대급 영지 ...', '데드퀸', '개를 낳았다', '세기말 풋사과...', '삼국지톡', '사신', '상남자', '낙향문사전', '소름일기', '언니, 이번 ...', '지옥 키우기', '더 게이머', '서울역 드루이드', '웅크', '히어로 킬러', '말년용사', '언다잉', 'A.I. 닥터', '온리호프', '그렇고 그런 ...', '여자를 사귀고...', '플레이어', '성스러운 그대...', '푸쉬오프', '이터널 포스', '선을 넘은 연애', '문제적 왕자님', '너의 미소가 ...', '절대복종', '후덜덜덜 남극...', '킬 더 드래곤', '메소드 연기법', '그 기사가 레...', '스포', '미드우트', '멜빈이 그들에...', '여름여자 하보이', '상위1%', '지니오패스', '이게 아닌데', '쿠쿠쿠쿠', '스토커의 하루', '거래', '악마라고 불러...', '네버엔딩달링', '로또 황녀님', '1초', '트럼프', '아찔한 전남편', '달이 없는 나라', '솔트앤페퍼', '몽홀', '비밀친구', '인피니티', '백년게임', '재앙의 날', '드래곤의 심장...', '태권보이', '짝사랑 마들렌', '너의 키스씬', '별빛 커튼콜', '천상의 주인', '리트리츠', '여름의 너에게', '합법해적 파르페', '팬시X팬시', '서울시 천사주의', '너에게 입덕중', '스치면 인연 ...']
fri 웹툰 개수 : 75
sat : ['99강화나무몽...', '호랑이형님', '2022 몰래...', '취사병 전설이...', '먹는 인생', '조조코믹스', '프리드로우', '여고생 드래곤', '망나니 소교주...', '이십팔세기 광팬', '은탄', '악몽의 형상', '아홉수 우리들', '스터디그룹', '청춘 블라썸', '나이트런', '반드시 해피엔딩', '간첩 18세', '작전명 순정', '윌유메리미', '나태 공자, ...', '세레나', '어글리후드', '소공녀 민트', '나를 바꿔줘', '존잘주의', '미나 이퀄', '탑코너', '물위의 우리', '아사', '남편 먹는 여자', '용두사망 소설...', '태백 : 튜토...', '좀비 파이트', '디펜스 게임의...', '홍시는 날 좋...', '용사참수인', '이계진입 리로...', '대충 캠퍼스로...', '같은 학교 친구', '엑스애쉬', '팬인데 왜요', '남편을 만렙으...', '폭군 남편과 ...', '지옥급식', '묘령의 황자', '공유몽', '완벽한 부부는...', '메트로헌터', '최면학교', '광해의 연인', '마법사가 죽음...', '최강부캐', '전생연분', '키스 식스 센스', '다비, 아찔하...', '은둔코인', '소년 검사', '복수를 위한 ...', '적월의 나라', '왕년엔 용사님', '중매쟁이 아가...', '모두 너였다', '청춘일지', '배달의 신', '키스의 여왕', '7FATES:...', '도사 가온', '스트릿 워크아웃', '아가사', '밤을 깨우는 ...', '숨겨진 성녀', '보고 있지?', '좋아해 아니 ...', '보듬보듬', '이건 그냥 연...', '아침을 지나 ...', '실버 쥬얼']
sat 웹툰 개수 : 78
sun : ['싸움독학', '독립일기', '입학용병', '약한영웅', '사형소년', '이번 생도 잘...', '수희0(tng...', '자매전쟁', '별이삼샵', '살아남은 로맨스', '천하제일인', '일타강사 백사부', '시월드가 내게...', '안녕, 나의 ...', '칼끝에 입술', '곱게 키웠더니...', '분신으로 자동...', '가비지타임', '판사 이한영', '노량진 공격대', '무서운게 딱좋...', '헬스던전', '내일', '약빨이 신선함', '아카데미에 위...', '오로지 너를 ...', '마법스크롤 상...', '어느날 갑자기...', '경자 전성시대', '폰투스 : 극...', '합격시켜주세용', '장풍전', '위닝샷!', '동생친구', '고백 취소도 ...', '손 안의 안단테', '백설을 위하여', '평행도시', '랑데뷰', '천치전능', '몸이 바뀌는 ...', '생존로그', '후궁 스캔들', '장미같은 소리', '결혼까지 망상...', '키미앤조이', '위험한 남편을...', '108명의 그...', '소녀재판', '마왕의 고백', '여우애담', '홍 의관의 은...', '나의 작은 서점', '데빌샷', '킬링킬러', '돌&아이', 'DARK MO...', '전설의 화석', '내곁엔 없을까', '생존고백', '하렘에서 살아...', '보스의 노골적...', '블러드 리벤저', '철수와 영희 ...', '마섹남 - 마...', '보통아이', '6월의 라벤더', '패션쇼', '샤인 스타', '마도', '사람은 고쳐 ...', '조선여우스캔들', '밀실 마피아 ...', '아마도, 굿모닝', '어떤소란', '거래하실래요?', '독신마법사 기...', '구해줘, 호구!']
sun 웹툰 개수 : 78

In [ ]:
week=['mon','tue','wed','tur','fri','sat','sun','dailyplus']

data={'day' : [],'name' : [], 'author' : [], 'point' : []}

for week in weeks:

    url='https://comic.naver.com/webtoon/weekdayList?week={}'.format(week)
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')
    tags_name=soup.select('ul.img_list li dl dt a') # 웹툰 제목
    tags_author=soup.select('ul.img_list li dl dd.desc a') # 작가
    tags_point=soup.select('div.rating_type strong') # 별점

    for i in tags_name:
        data['day'].append(week)
        data['name'].append(i.text)

    for i in tags_author:
        data['author'].append(i.text)

    for i in tags_point:
        data['point'].append(i.text)

df=pd.DataFrame(data)
df.to_csv('웹툰 제목, 작가, 평점.csv')

In [ ]:
weeks=['mon','tue','wed','tur','fri','sat','sun','dailyplus']

data={'day' : [],'name' : [], 'author' : [], 'point' : []}

for week in list:

    url='https://comic.naver.com/webtoon/weekdayList?week={}'.format(week)
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')
    tags_name=soup.select('ul.img_list li dl dt a') # 웹툰 제목
    tags_author=soup.select('ul.img_list li dl dd.desc a') # 작가
    tags_point=soup.select('div.rating_type strong') # 별점

    for i in range(len(tags_name)):
        data['day'].append(week)
        data['name'].append(tags_name[i].text)
        data['author'].append(tags_author[i].text)
        data['point'].append(tags_point[i].text)

df=pd.DataFrame(data)
df

           day        name          author point
0          mon         참교육       채용택 / 한가람  9.86
1          mon     뷰티풀 군바리        설이 / 윤성원  9.81
2          mon     퀘스트지상주의        박태준 만화회사  9.80
3          mon  장씨세가 호위...       김인호 / 조형근  9.93
4          mon      윈드브레이커             조용석  9.84
..         ...         ...             ...   ...
663  dailyplus     사파리 로맨스     yoshua / 윤정  9.67
664  dailyplus     투 두 리스트  RYO. / FLEWing  9.77
665  dailyplus      사생활 체크         리기 / 와치  9.71
666  dailyplus         비타운        요신 / 김선우  8.08
667  dailyplus  열린 지옥문 ...              녹밤  9.51

[668 rows x 4 columns]

In [ ]:
A=df[df['point']==df['point'].max()]
A.index=range(A.count()[0])
A

          day        name    author point
0         mon       호랑신랑뎐      고추참치  9.98
1         mon      똑 닮은 딸        이담  9.98
2         tue      마루는 강쥐        모죠  9.98
3         tue  하루만 네가 ...         삼  9.98
4         tue         올가미       해무리  9.98
5         tue      견우와 선녀       안수민  9.98
6         wed  마른 가지에 ...  화음 / 달새울  9.98
7         tur  세기말 풋사과...        순끼  9.98
8         tur        푸쉬오프      허5파6  9.98
9         fri  세기말 풋사과...        순끼  9.98
10        fri        푸쉬오프      허5파6  9.98
11        sat     아홉수 우리들       수박양  9.98
12        sat       어글리후드        미애  9.98
13        sat      물위의 우리   뱁새 / 왈패  9.98
14        sun  이번 생도 잘...        이혜  9.98
15        sun    살아남은 로맨스        이연  9.98
16        sun  시월드가 내게...  승우 / 한윤설  9.98
17        sun          내일        라마  9.98
18        sun     합격시켜주세용        이온  9.98
19  dailyplus    등교하는 근식이   무지개 멍멍이  9.98

In [ ]:
weeks=['mon','tue','wed','tur','fri','sat','sun','dailyplus']

data={'day' : [],'name' : [], 'author' : [], 'point' : []}

for week in list:

    url='https://comic.naver.com/webtoon/weekdayList?week='+week
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')
    tags_name=soup.select('ul.img_list li dl dt a') # 웹툰 제목
    tags_author=soup.select('ul.img_list li dl dd.desc a') # 작가
    tags_point=soup.select('div.rating_type strong') # 별점

    for name, author, point in zip(tags_name, tags_author, tags_point): # zip함수로 묶어서
        data['day'].append(week)
        data['name'].append(name.text)
        data['author'].append(author.text)
        data['point'].append(point.text)

df=pd.DataFrame(data)
df.to_csv('웹툰1.csv')

           day        name          author point
0          mon         참교육       채용택 / 한가람  9.86
1          mon     뷰티풀 군바리        설이 / 윤성원  9.81
2          mon     퀘스트지상주의        박태준 만화회사  9.80
3          mon  장씨세가 호위...       김인호 / 조형근  9.93
4          mon      윈드브레이커             조용석  9.84
..         ...         ...             ...   ...
663  dailyplus     사파리 로맨스     yoshua / 윤정  9.67
664  dailyplus     투 두 리스트  RYO. / FLEWing  9.77
665  dailyplus      사생활 체크         리기 / 와치  9.71
666  dailyplus         비타운        요신 / 김선우  8.08
667  dailyplus  열린 지옥문 ...              녹밤  9.51

[668 rows x 4 columns]

           day        name          author point
0          mon         참교육       채용택 / 한가람  9.86
1          mon     뷰티풀 군바리        설이 / 윤성원  9.81
2          mon     퀘스트지상주의        박태준 만화회사  9.80
3          mon  장씨세가 호위...       김인호 / 조형근  9.93
4          mon      윈드브레이커             조용석  9.84
..         ...         ...             ...   ...
663  dailyplus     사파리 로맨스     yoshua / 윤정  9.67
664  dailyplus     투 두 리스트  RYO. / FLEWing  9.77
665  dailyplus      사생활 체크         리기 / 와치  9.71
666  dailyplus         비타운        요신 / 김선우  8.08
667  dailyplus  열린 지옥문 ...              녹밤  9.51

[668 rows x 4 columns]

같은 부류의 경우 html의 href가 리소스경로로만 입력됨
- 눌러서 링크 확인<a onclick="nclk_v2(event,'dna.tuesday')" href="/webtoon/weekdayList?week=mon">화요웹툰</a>

url=프로토콜/주소값/리소스경로/쿼리스트링
- a 클래스는 하이퍼링크

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

week_link=[]

url='https://comic.naver.com/webtoon/weekdayList?week=mon'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')

# a_tags=soup.select('ul.category_tab a')
# for idx, a_tag in enumerate(a_tags):
#     if idx:
#         week_link.append('https://comic.naver.com'+a_tag['href'])

# 위 아래의 a_tags를 가져오는 방식은 동일하다

a_tags=soup.select('ul.category_tab a')[1:] # select 함수는 리스트의 형태로 가져옴

for a_tag in a_tags:
        week_link.append('https://comic.naver.com'+a_tag['href'])

data={'title':[],'author':[], 'rating':[]}

for url_target in week_link:
    resp=requests.get(url_target)
    soup=BeautifulSoup(resp.content, 'lxml')
    title_tags=soup.select('ul.img_list li dl dt a')
    author_tags=soup.select('ul.img_list dd.desc a') # ul.img_listli dl dd.desc a
    rating_tags=soup.select('ul.img_list div.rating_type strong') # ul.img_listli dl dd div.rating_type strong

    for title, author, rating in zip(title_tags, author_tags, rating_tags):
        data['title'].append(title['title'])
        data['author'].append(author.text)
        data['rating'].append(rating.text)

df=pd.DataFrame(data)
df

         title          author rating
0          참교육       채용택 / 한가람   9.86
1      뷰티풀 군바리        설이 / 윤성원   9.81
2      퀘스트지상주의        박태준 만화회사   9.80
3    장씨세가 호위무사       김인호 / 조형근   9.93
4       윈드브레이커             조용석   9.84
..         ...             ...    ...
672    사파리 로맨스     yoshua / 윤정   9.67
673    투 두 리스트  RYO. / FLEWing   9.77
674     사생활 체크         리기 / 와치   9.71
675        비타운        요신 / 김선우   8.08
676  열린 지옥문 닫힘              녹밤   9.51

[677 rows x 3 columns]

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

url='https://comic.naver.com/webtoon/weekdayList?week=mon'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')
a_tags=soup.select('ul.category_tab a')[1:]

week_link=[]

for a_tag in a_tags:
    week_link.append('https://comic.naver.com'+a_tag['href'])

data={'title':[],'author':[], 'rating':[], 'week':[]}

for url_target in week_link:
    resp=requests.get(url_target)
    soup=BeautifulSoup(resp.content, 'lxml')
    title_tags=soup.select('ul.img_list li dl dt a')
    author_tags=soup.select('ul.img_list dd.desc a')
    rating_tags=soup.select('ul.img_list div.rating_type strong')

    for title, author, rating in zip(title_tags, author_tags, rating_tags):
        data['title'].append(title['title'])
        data['author'].append(author.text)
        data['rating'].append(rating.text)
        data['week'].append(url_target.split('=')[1])

df=pd.DataFrame(data)
df

         title          author rating       week
0          참교육       채용택 / 한가람   9.86        mon
1      뷰티풀 군바리        설이 / 윤성원   9.81        mon
2      퀘스트지상주의        박태준 만화회사   9.80        mon
3    장씨세가 호위무사       김인호 / 조형근   9.93        mon
4       윈드브레이커             조용석   9.84        mon
..         ...             ...    ...        ...
672    사파리 로맨스     yoshua / 윤정   9.67  dailyplus
673    투 두 리스트  RYO. / FLEWing   9.77  dailyplus
674     사생활 체크         리기 / 와치   9.71  dailyplus
675        비타운        요신 / 김선우   8.08  dailyplus
676  열린 지옥문 닫힘              녹밤   9.51  dailyplus

[677 rows x 4 columns]

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

url='https://comic.naver.com/webtoon/weekdayList?week=mon'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')
a_tags=soup.select('ul.category_tab a')[1:]

weeks = []
week_link=[]

for a_tag in a_tags:
    weeks.append(a_tag.text[:-3]) # [월,화,수,목,금,토,일,매일]
    week_link.append('https://comic.naver.com' + a_tag['href']) # [각 요일별 url주소]

data={'제목':[],'작가':[], '평점':[], '요일':[]}

for week, url_target in zip(weeks, week_link):
    resp=requests.get(url_target)
    soup=BeautifulSoup(resp.content, 'lxml')
    title_tags=soup.select('ul.img_list li dl dt a')
    author_tags=soup.select('ul.img_list dd.desc a')
    rating_tags=soup.select('ul.img_list div.rating_type strong')

    for title, author, rating in zip(title_tags, author_tags, rating_tags):
        data['제목'].append(title['title'])
        data['작가'].append(author.text)
        data['평점'].append(rating.text)
        data['요일'].append(week)

df=pd.DataFrame(data)
df

            제목              작가    평점  요일
0          참교육       채용택 / 한가람  9.86   월
1      뷰티풀 군바리        설이 / 윤성원  9.81   월
2      퀘스트지상주의        박태준 만화회사  9.80   월
3    장씨세가 호위무사       김인호 / 조형근  9.93   월
4       윈드브레이커             조용석  9.84   월
..         ...             ...   ...  ..
672    사파리 로맨스     yoshua / 윤정  9.67  매일
673    투 두 리스트  RYO. / FLEWing  9.77  매일
674     사생활 체크         리기 / 와치  9.71  매일
675        비타운        요신 / 김선우  8.08  매일
676  열린 지옥문 닫힘              녹밤  9.51  매일

[677 rows x 4 columns]

In [ ]:
df.to_csv('네이버웹툰정보.csv', index=False)

In [ ]:
naver_toons = pd.read_csv('네이버웹툰정보.csv', index_col='요일')
naver_toons[['작가','제목','평점']]

                작가         제목    평점
요일
월        채용택 / 한가람        참교육  9.86
월         설이 / 윤성원    뷰티풀 군바리  9.81
월         박태준 만화회사    퀘스트지상주의  9.80
월        김인호 / 조형근  장씨세가 호위무사  9.93
월              조용석     윈드브레이커  9.84
..             ...        ...   ...
매일     yoshua / 윤정    사파리 로맨스  9.67
매일  RYO. / FLEWing    투 두 리스트  9.77
매일         리기 / 와치     사생활 체크  9.71
매일        요신 / 김선우        비타운  8.08
매일              녹밤  열린 지옥문 닫힘  9.51

[677 rows x 3 columns]

In [ ]:
naver_toons.columns=['제목','작가','평점']
naver_toons

           제목              작가    평점
요일
월         참교육       채용택 / 한가람  9.86
월     뷰티풀 군바리        설이 / 윤성원  9.81
월     퀘스트지상주의        박태준 만화회사  9.80
월   장씨세가 호위무사       김인호 / 조형근  9.93
월      윈드브레이커             조용석  9.84
..        ...             ...   ...
매일    사파리 로맨스     yoshua / 윤정  9.67
매일    투 두 리스트  RYO. / FLEWing  9.77
매일     사생활 체크         리기 / 와치  9.71
매일        비타운        요신 / 김선우  8.08
매일  열린 지옥문 닫힘              녹밤  9.51

[677 rows x 3 columns]

이미지 크롤링

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
url='https://shared-comic.pstatic.net/thumb/webtoon/758037/thumbnail/thumbnail_IMAG10_a2297504-4912-4c7e-a5a8-524d6fc77103.jpg'
resp=requests.get(url)
# resp.content -> 이게 이미지를 뜻함
# html 안에 이미지는 없다. 이미지의 src(주소값)만 있음
# 이미지 전체를 가져오기에 select할 필요 없이 사용하기 때문에 BeautifulSoup 및 select를 사용하지 않아도 된다.

입출력 헝식:
- 저장하다/불러오다
- 텍스트파일을/바이너리파일을

In [ ]:
# with open('경로+파일이름', '입출력형식') as f:
#     f.수행함수(대상)

In [ ]:
img_src='https://shared-comic.pstatic.net/thumb/webtoon/758037/thumbnail/thumbnail_IMAG21_15cb2611-34c0-4f02-a689-41d0b1016579.jpg'
resp=requests.get(img_src)
resp

In [ ]:
with open('thumb_hogu.jpg','wb') as f:
    f.write(resp.content)
# w -> wirte
# wb -> 바이너리파일을 저장
# wt -> 텍스트를 저장
# rt -> read text
# f.write(저장하고싶은 대상)

In [ ]:
url='https://comic.naver.com/webtoon/weekday'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')
thumb_tags=soup.select('div.list_area.daily_all div.thumb img') # 이미지 링크가 포함된 태그들을 리스트로 만듬

img_srcs=[]

for thumb_tag in thumb_tags: # 이미지링크가 포함된 태그에서 클래스 src를 통해 이미지 링크 추출
    img_srcs.append(thumb_tag['src'])

In [ ]:
for idx,src in enumerate(img_srcs):
    # 덮어씨워서 지워지는걸 방지하기 위해 index값을 가져와서 index 값으로 저장하기 위해
    resp=requests.get(src)

    with open('thumb_img_{}.jpg'.format(idx),'wb') as f:
            # 'thumb_img_' + str(idx) + '.jpg'
            # 'thumb_img_{}.jpg'.format(idx)
        f.write(resp.content)
    break # 하나만 해보기위해
    # 순서대로 되지가 않음

In [ ]:
for idx,src in enumerate(img_srcs):
    resp=requests.get(src)

    with open('thumb_img_{:03}.jpg'.format(idx),'wb') as f:
        f.write(resp.content)
    break
    # 순서대로 저장하기 위해 사용
        # {:3} -> 1,2,3 -> 3자리를 채워서 순서대로됨
        # {:03} -> 001, 002, 003

파일 경로만들기

In [ ]:
!mkdir thumb_image

In [ ]:
for idx,src in enumerate(img_srcs):
    resp=requests.get(src)

    with open('thumb_image/thumb_img_{:03}.jpg'.format(idx),'wb') as f: # 파일경로/파일이름
        f.write(resp.content)
    break

iframe 가져오기

In [ ]:
import requests
from bs4 import BeautifulSoup

url='https://finance.naver.com/sise/sise_index_day.naver?code=KPI200'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')
a_tag=soup.select('td.pgRR a') # 리스트형태
pg_rr_url=a_tag[0]['href'] # 리스트형태여서 인덱스를 꺼네고 클래스 href 값을 꺼냄
la_pg_nu=int(pg_rr_url.split("=")[-1])

693

네이버 증권페이지에서 일별시세 정보 가져오기

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
url='https://finance.naver.com/sise/sise_index_day.naver?code=KPI200'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')

In [ ]:
# 날짜
날짜_list=[]
날짜_tags=soup.select('tr td.date')

for i in 날짜_tags:
    날짜_list.append(i.text.strip())
날짜_list

['2022.10.28',
 '2022.10.27',
 '2022.10.26',
 '2022.10.25',
 '2022.10.24',
 '2022.10.21']

In [ ]:
# 체결가 등락률 거래량 거래대금
tab_1=soup.select('tr td.number_1')

체결가=tab_1[::4]
등락률=tab_1[1::4]
거래량=tab_1[2::4]
거래대금=tab_1[3::4]

체결가_list=[]
등락률_list=[]
거래량_list=[]
거래대금_list=[]

for i,j,k,l in zip(체결가, 등락률, 거래량, 거래대금):
    체결가_list.append(i.text.strip())
    등락률_list.append(j.text.strip())
    거래량_list.append(k.text.strip())
    거래대금_list.append(l.text.strip())

print(체결가_list)
print(등락률_list)
print(거래량_list)
print(거래대금_list)

['295.06', '298.82', '293.85', '291.58', '291.47', '288.57']
['-1.26%', '+1.69%', '+0.78%', '+0.04%', '+1.00%', '-0.01%']
['131,077', '176,203', '122,301', '116,351', '116,175', '102,369']
['6,484,976', '6,808,554', '5,868,014', '5,506,858', '5,372,980', '4,677,515']

In [ ]:
# columns 만들기
열이름=[]

for i in soup.select('tr th'):
    열이름.append(i.text.strip())
열이름

['날짜', '체결가', '전일비', '등락률', '거래량(천주)', '거래대금(백만)']

In [ ]:
# 전일비 만들기
전일비_tags=soup.select('td.rate_down span.tah.p11')
rate_down_list=[]
for i in 전일비_tags:
    rate_down_list.append(float(i.text.strip()))


화살표_tags=soup.select('td.rate_down img')
화살표_list=[]
for i in 화살표_tags:
    화살표_list.append((i['src'].split("_")[-1].strip('.gif')))

전일비_list=[]

for i,j in zip(화살표_list, rate_down_list):
    if i=='down':
        전일비_list.append(-j)
    else:
        전일비_list.append(j)


print(rate_down_list)
print(화살표_list)
print(전일비_list)

[3.76, 4.97, 2.27, 0.11, 2.9, 0.04]
['down', 'up', 'up', 'up', 'up', 'down']
[-3.76, 4.97, 2.27, 0.11, 2.9, -0.04]

['날짜', '체결가', '전일비', '등락률', '거래량(천주)', '거래대금(백만)']

In [ ]:
print(체결가_list)
print(전일비_list)
print(등락률_list)
print(거래량_list)
print(거래대금_list)
print(날짜_list)
print(열이름)

['295.06', '298.82', '293.85', '291.58', '291.47', '288.57']
[-3.76, 4.97, 2.27, 0.11, 2.9, -0.04]
['-1.26%', '+1.69%', '+0.78%', '+0.04%', '+1.00%', '-0.01%']
['131,077', '176,203', '122,301', '116,351', '116,175', '102,369']
['6,484,976', '6,808,554', '5,868,014', '5,506,858', '5,372,980', '4,677,515']
['2022.10.28', '2022.10.27', '2022.10.26', '2022.10.25', '2022.10.24', '2022.10.21']
['날짜', '체결가', '전일비', '등락률', '거래량(천주)', '거래대금(백만)']

In [ ]:
import pandas as pd

data=[날짜_list, 체결가_list, 전일비_list, 등락률_list, 거래량_list, 거래대금_list]
table=pd.DataFrame(data, index=열이름).transpose()
table

           날짜     체결가   전일비     등락률  거래량(천주)   거래대금(백만)
0  2022.10.28  295.06 -3.76  -1.26%  131,077  6,484,976
1  2022.10.27  298.82  4.97  +1.69%  176,203  6,808,554
2  2022.10.26  293.85  2.27  +0.78%  122,301  5,868,014
3  2022.10.25  291.58  0.11  +0.04%  116,351  5,506,858
4  2022.10.24  291.47   2.9  +1.00%  116,175  5,372,980
5  2022.10.21  288.57 -0.04  -0.01%  102,369  4,677,515

In [ ]:
# 강사님 풀이
dates, prices, diffs, rates, volumes, amounts = [], [], [], [], [], []

url = 'https://finance.naver.com/sise/sise_index_day.naver?code=KPI200&page=1'

resp = requests.get(url)
resp

soup = BeautifulSoup(resp.content, 'lxml')
date_tags = soup.select('td.date')

num_tags = soup.select('td.number_1')
price_tags = num_tags[::4]
rate_tags = num_tags[1::4]
vol_tags = num_tags[2::4]
amnt_tags = num_tags[3::4]

diff_tags = soup.select('td.rate_down span.tah.p11')

for i in range(6):
    dates.append(date_tags[i].text) # 날짜
    prices.append(price_tags[i].text) # 체결가

    # 전일비 
    diff = diff_tags[i].text.strip()
    if diff_tags[i]['class'][-1] == 'nv01': # 하락값에는 음수 처리
        diff = f'-{diff}'
    diffs.append(diff)
    rates.append(rate_tags[i].text.strip()) # 등락률
    volumes.append(vol_tags[i].text) # 거래량
    amounts.append(amnt_tags[i].text) # 거래대금
dates, prices, diffs, rates, volumes, amounts

(['2022.10.28',
  '2022.10.27',
  '2022.10.26',
  '2022.10.25',
  '2022.10.24',
  '2022.10.21'],
 ['295.06', '298.82', '293.85', '291.58', '291.47', '288.57'],
 ['-3.76', '4.97', '2.27', '0.11', '2.90', '-0.04'],
 ['-1.26%', '+1.69%', '+0.78%', '+0.04%', '+1.00%', '-0.01%'],
 ['129,003', '176,203', '122,301', '116,351', '116,175', '102,369'],
 ['6,379,576',
  '6,808,554',
  '5,868,014',
  '5,506,858',
  '5,372,980',
  '4,677,515'])

과제: 코스피 200 전체페이지

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm

In [2]:
# 마지막 페이지 추출하기
url='https://finance.naver.com/sise/sise_index_day.naver?code=KPI200&page=1'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')
last_pg=int(soup.select('td.pgRR a')[0]['href'].split('page=')[-1])

df_list=[]

for pg in tqdm(range(1,last_pg+1)):
    url='https://finance.naver.com/sise/sise_index_day.naver?code=KPI200&page={}'.format(pg)
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')

    data={}

    summary_tags=soup.select('tr th') # 날짜, 체결가 전일비, 등락률, 거래량(천주), 거래대금(백만)

    for key in summary_tags: # 항목 이름 만들기(딕셔너리 key추가)
        data[f'{key.text}']=[]

    date_tags=soup.select('td.date') # 날짜 태그들
    price_tags=soup.select('td.number_1')[0::4] # 체결가 태그들
    rate_days=soup.select('td.rate_down span.tah.p11') # 전일비 태그들 인데 span.tah.p11 까지 가져오면 마지막페이지에서 전일비만 5개를 가져옴
    rate_per=soup.select('td.number_1')[1::4] # 등락률 태그들
    trade_vol=soup.select('td.number_1')[2::4] # 거래량 태그들
    trade_pri=soup.select('td.number_1')[3::4] # 거래대금 태그들
        
    tags_len=min([len(date_tags), len(price_tags), len(rate_days), len(rate_per), len(trade_vol), len(trade_pri)])
    # 전일비 태그들 인데 span.tah.p11 까지 가져오면 마지막페이지에서 다른애들은 6개를 가져와도 전일비만 5개를 가져옴

    for i in range(tags_len): # 비어있는 data dictionary 채우기
        data['날짜'].append(date_tags[i].text)
        data['체결가'].append(price_tags[i].text)

        if rate_days[i]['class'][-1]=='red02':
            data['전일비'].append("+"+rate_days[i].text.strip())
        else:
            data['전일비'].append("-"+rate_days[i].text.strip())

        data['등락률'].append(rate_per[i].text.strip())
        data['거래량(천주)'].append(trade_vol[i].text)
        data['거래대금(백만)'].append(trade_pri[i].text)

    df=pd.DataFrame(data)
    df_list.append(df)

df1=pd.concat(df_list, ignore_index=True)

100%|██████████| 693/693 [02:12<00:00,  5.24it/s]

In [ ]:
693*6-1
# 마지막 페이지는 5개

4157

In [4]:
df1

              날짜     체결가    전일비     등락률  거래량(천주)   거래대금(백만)
0     2022.10.28  295.06  -3.76  -1.26%  131,077  6,484,976
1     2022.10.27  298.82  +4.97  +1.69%  176,203  6,808,554
2     2022.10.26  293.85  +2.27  +0.78%  122,301  5,868,014
3     2022.10.25  291.58  +0.11  +0.04%  116,351  5,506,858
4     2022.10.24  291.47  +2.90  +1.00%  116,175  5,372,980
...          ...     ...    ...     ...      ...        ...
4152  2006.01.09  180.30  -0.57  -0.32%  191,222  4,641,279
4153  2006.01.06  180.87  +2.05  +1.15%  206,313  4,609,858
4154  2006.01.05  178.82  -1.09  -0.61%  206,332  5,522,148
4155  2006.01.04  179.91  +1.10  +0.62%  188,841  5,360,812
4156  2006.01.03  178.81  +0.52  +0.29%  158,041  4,161,549

[4157 rows x 6 columns]

In [11]:
df1.loc[::-1]

              날짜     체결가    전일비     등락률  거래량(천주)   거래대금(백만)
4156  2006.01.03  178.81  +0.52  +0.29%  158,041  4,161,549
4155  2006.01.04  179.91  +1.10  +0.62%  188,841  5,360,812
4154  2006.01.05  178.82  -1.09  -0.61%  206,332  5,522,148
4153  2006.01.06  180.87  +2.05  +1.15%  206,313  4,609,858
4152  2006.01.09  180.30  -0.57  -0.32%  191,222  4,641,279
...          ...     ...    ...     ...      ...        ...
4     2022.10.24  291.47  +2.90  +1.00%  116,175  5,372,980
3     2022.10.25  291.58  +0.11  +0.04%  116,351  5,506,858
2     2022.10.26  293.85  +2.27  +0.78%  122,301  5,868,014
1     2022.10.27  298.82  +4.97  +1.69%  176,203  6,808,554
0     2022.10.28  295.06  -3.76  -1.26%  131,077  6,484,976

[4157 rows x 6 columns]

In [14]:
range(len(list(df1.index)))

range(0, 4157)

In [17]:
df2=df1.loc[::-1]
df2.index=range(len(list(df1.index)))
df2

              날짜     체결가    전일비     등락률  거래량(천주)   거래대금(백만)
0     2006.01.03  178.81  +0.52  +0.29%  158,041  4,161,549
1     2006.01.04  179.91  +1.10  +0.62%  188,841  5,360,812
2     2006.01.05  178.82  -1.09  -0.61%  206,332  5,522,148
3     2006.01.06  180.87  +2.05  +1.15%  206,313  4,609,858
4     2006.01.09  180.30  -0.57  -0.32%  191,222  4,641,279
...          ...     ...    ...     ...      ...        ...
4152  2022.10.24  291.47  +2.90  +1.00%  116,175  5,372,980
4153  2022.10.25  291.58  +0.11  +0.04%  116,351  5,506,858
4154  2022.10.26  293.85  +2.27  +0.78%  122,301  5,868,014
4155  2022.10.27  298.82  +4.97  +1.69%  176,203  6,808,554
4156  2022.10.28  295.06  -3.76  -1.26%  131,077  6,484,976

[4157 rows x 6 columns]

In [ ]:
df1.to_csv('Kospi200일별시세.csv',encoding='utf-8-sig', index=False)

In [ ]:
df2=pd.read_csv('/content/Kospi200일별시세.csv')
df2

              날짜     체결가   전일비     등락률  거래량(천주)   거래대금(백만)
0     2022.10.28  295.06 -3.76  -1.26%  131,077  6,484,976
1     2022.10.27  298.82  4.97  +1.69%  176,203  6,808,554
2     2022.10.26  293.85  2.27  +0.78%  122,301  5,868,014
3     2022.10.25  291.58  0.11  +0.04%  116,351  5,506,858
4     2022.10.24  291.47  2.90  +1.00%  116,175  5,372,980
...          ...     ...   ...     ...      ...        ...
4152  2006.01.09  180.30 -0.57  -0.32%  191,222  4,641,279
4153  2006.01.06  180.87  2.05  +1.15%  206,313  4,609,858
4154  2006.01.05  178.82 -1.09  -0.61%  206,332  5,522,148
4155  2006.01.04  179.91  1.10  +0.62%  188,841  5,360,812
4156  2006.01.03  178.81  0.52  +0.29%  158,041  4,161,549

[4157 rows x 6 columns]

과제: 네이버 웹툰 장르별 제목/작가/평점

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm

url='https://comic.naver.com/webtoon/genre?genre=episode'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')

data={}
genre_list=[]
genre_kor_list=[]
genre_tags=soup.select('ul.spot li a')

for i in tqdm(genre_tags):

    genre_kor=i.text.strip()
    genre_kor_list.append(genre_kor)

    genre_eng=i['href'].split('genre=')[-1]
    genre_list.append(genre_eng)

    data[f'{genre_eng}']=[]

for genre in tqdm(genre_list):

    url='https://comic.naver.com/webtoon/genre?genre={}'.format(genre)
    resp=requests.get(url)

    soup=BeautifulSoup(resp.content, 'lxml')
    title_tags=soup.select('ul li dl dt a')
    author_tags=soup.select('ul li dl dd.desc a')
    rating_tags=soup.select('div.rating_type strong')

    for i in range(len(title_tags)):
        title=title_tags[i]['title']
        author=author_tags[i].text
        rating=rating_tags[i].text.strip()
        data[f'{genre}'].append(f'작가: {title} \n 제목: {author} \n 평점: {rating}')

data1={key:pd.Series(value) for key, value in data.items()}
# 리스트와 딕셔너리는 서로 길이가 다르면 데이터프레임으로 만들어지지 않지만 시리즈는 길이가 달라도 빈곳이 NaN칸으로 채워져서 만들어진다.

df=pd.DataFrame(data1)
df.columns=genre_kor_list

100%|██████████| 13/13 [00:00<00:00, 9589.51it/s]
100%|██████████| 13/13 [00:06<00:00,  2.11it/s]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1702 entries, 0 to 1701
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   에피소드    204 non-null    object
 1   옴니버스    113 non-null    object
 2   스토리     1702 non-null   object
 3   일상      78 non-null     object
 4   개그      138 non-null    object
 5   판타지     349 non-null    object
 6   액션      168 non-null    object
 7   드라마     431 non-null    object
 8   순정      505 non-null    object
 9   감성      35 non-null     object
 10  스릴러     250 non-null    object
 11  무협/사극   42 non-null     object
 12  스포츠     23 non-null     object
dtypes: object(13)
memory usage: 173.0+ KB

In [ ]:
df.to_csv('장르별웹툰.csv', encoding='utf-8-sig', index=False)

In [ ]:
pd.read_csv('장르별웹툰.csv')

,에피소드,옴니버스,스토리,일상,개그,판타지,액션,드라마,순정,감성,스릴러,무협/사극,스포츠
0,작가: 대학원 탈출일지 \n 제목: 요다 \n 평점: 9.97,작가: 먹는 인생 \n 제목: 홍끼 \n 평점: 9.96,작가: 99강화나무몽둥이 \n 제목: 홍실 / 지페리 \n 평점: 9.78,작가: 대학원 탈출일지 \n 제목: 요다 \n 평점: 9.97,작가: 마루는 강쥐 \n 제목: 모죠 \n 평점: 9.98,작가: 99강화나무몽둥이 \n 제목: 홍실 / 지페리 \n 평점: 9.78,작가: 김부장 \n 제목: 박태준 만화회사 ... \n 평점: 9.24,작가: 외모지상주의 \n 제목: 박태준 \n 평점: 9.47,작가: 내 남편과 결혼해줘 \n 제목: LICO / 성소작 \n 평점: 9.95,작가: 웅크 \n 제목: 나유진 \n 평점: 9.97,작가: 퍼니게임 \n 제목: 배진수 \n 평점: 9.83,작가: 나노마신 \n 제목: 현절무 / 금강불... \n 평점: 9.92,작가: 윈드브레이커 \n 제목: 조용석 \n 평점: 9.84
1,작가: 마루는 강쥐 \n 제목: 모죠 \n 평점: 9.98,작가: 조조코믹스 \n 제목: 이동건 \n 평점: 9.97,작가: 김부장 \n 제목: 박태준 만화회사 ... \n 평점: 9.24,작가: 먹는 인생 \n 제목: 홍끼 \n 평점: 9.96,작가: 나쁜사람 \n 제목: 둠스 \n 평점: 9.68,작가: 전지적 독자 시점 \n 제목: UMI / 슬리피... \n 평점: 9.95,작가: 참교육 \n 제목: 채용택 / 한가람 \n 평점: 9.86,작가: 뷰티풀 군바리 \n 제목: 설이 / 윤성원 \n 평점: 9.81,작가: 여신강림 \n 제목: 야옹이 \n 평점: 9.38,작가: 6월의 라벤더 \n 제목: 밤희 / 게살 \n 평점: 9.94,"작가: 사형소년 \n 제목: 박태준만화회사, ... \n 평점: 9.90",작가: 광마회귀 \n 제목: JP / 이히 /... \n 평점: 9.97,작가: 격기3반 \n 제목: 이학 \n 평점: 9.53
2,작가: 2022 몰래보는 로맨스 \n 제목: 웹툰작가 \n 평점: 9.85,작가: 언다잉 \n 제목: 임목원 \n 평점: 9.87,작가: 내 남편과 결혼해줘 \n 제목: LICO / 성소작 \n 평점: 9.95,작가: 독립일기 \n 제목: 자까 \n 평점: 9.97,작가: 이십팔세기 광팬 \n 제목: 컷부 \n 평점: 9.90,작가: 호랑이형님 \n 제목: 이상규 \n 평점: 9.95,작가: 싸움독학 \n 제목: 박태준 만화회사 ... \n 평점: 9.72,작가: 연애혁명 \n 제목: 232 \n 평점: 9.86,작가: 2022 몰래보는 로맨스 \n 제목: 웹툰작가 \n 평점: 9.85,작가: 슈퍼스타 천대리 \n 제목: 박경원 / 이재국... \n 평점: 9.79,작가: 악몽의 형상 \n 제목: 김용키 \n 평점: 9.92,작가: 장씨세가 호위무사 \n 제목: 김인호 / 조형근 \n 평점: 9.93,작가: 빌드업 \n 제목: 911 \n 평점: 9.83
3,작가: 약한영웅 \n 제목: 서패스 / 김진석 \n 평점: 9.82,작가: 소름일기 \n 제목: siAm \n 평점: 9.87,작가: 참교육 \n 제목: 채용택 / 한가람 \n 평점: 9.86,"작가: 안녕, 나의 수집 \n 제목: 하린 \n 평점: 9.95",작가: 여자를 사귀고 싶다 \n 제목: 노갓량 / 영오 \n 평점: 9.22,작가: 갓 오브 하이스쿨 \n 제목: 박용제 \n 평점: 9.64,작가: 헬퍼 2 : 킬베로스 \n 제목: 삭 \n 평점: 8.78,작가: 퀘스트지상주의 \n 제목: 박태준 만화회사 \n 평점: 9.80,작가: 어쩌다보니 천생연분 \n 제목: 꿀타래 / 담초 \n 평점: 9.97,작가: 연우의 순정 \n 제목: 이솔 \n 평점: 9.98,작가: 똑 닮은 딸 \n 제목: 이담 \n 평점: 9.98,작가: 천마육성 \n 제목: 광휘 / 조형근 \n 평점: 9.88,작가: 가비지타임 \n 제목: 2사장 \n 평점: 9.96
4,작가: 비즈니스 여친 \n 제목: 루즌아 / 서해 \n 평점: 9.74,작가: 기묘한 만화 \n 제목: 몬킬 \n 평점: 9.57,작가: 외모지상주의 \n 제목: 박태준 \n 평점: 9.47,작가: 윌유메리미 \n 제목: 마인드C \n 평점: 9.92,작가: 죄송한데 주인공이세요? \n 제목: 조석 \n 평점: 9.95,작가: 내가 키운 S급들 \n 제목: seri / 비완... \n 평점: 9.93,작가: 입학용병 \n 제목: YC / 락현 \n 평점: 9.89,작가: 팔이피플 \n 제목: 매미 / 희세 \n 평점: 9.94,작가: 1을 줄게 \n 제목: 김계란 \n 평점: 9.96,작가: 밥 먹고 갈래요? \n 제목: 오묘 \n 평점: 9.97,작가: 언다잉 \n 제목: 임목원 \n 평점: 9.87,작가: 무림서부 \n 제목: 웨스트 / 정한길... \n 평점: 9.89,작가: 빅맨 \n 제목: 하하영 \n 평점: 9.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1697,NaN,NaN,작가: 102030 \n 제목: H / JMS \n 평점: 8.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1698,NaN,NaN,작가: 파우스트 인 러브 \n 제목: 허니맨 / 손팡 \n 평점: 9.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1699,NaN,NaN,작가: 그림자 잡기 \n 제목: 최날 \n 평점: 9.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1700,NaN,NaN,작가: 천년간 노려왔습니다 \n 제목: 수빈 \n 평점: 9.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1701,NaN,NaN,작가: 완벽한 파트너 \n 제목: 산차 / 오하라 \n 평점: 9.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN