In [65]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from tqdm import tqdm

In [4]:
url='https://comic.naver.com/webtoon/genre?genre=episode'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')

In [66]:
url='https://comic.naver.com/webtoon/genre?genre=episode'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')
genre_tags=soup.select('ul.spot a')

genre_dic={}
genre_kor_list=[]
for genre in tqdm(genre_tags):
    genre_eng=genre['href'].split('genre=')[-1]
    genre_dic[f'{genre_eng}']=[]
    genre_kor_list.append(genre.text)

    url='https://comic.naver.com/webtoon/genre?genre={}'.format(genre_eng)
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')

    title_tags=soup.select('div.thumb a') # 제목
    author_tags=soup.select('dd.desc a') # 작가
    rating_tags=soup.select('div.rating_type strong') # 평점

    for i in range(len(title_tags)):
        title=title_tags[i]['title']
        author=author_tags[i].text
        rating=rating_tags[i].text
        genre_dic[f'{genre_eng}'].append("/".join([title,author,rating]))

data={key:pd.Series(value) for key, value in genre_dic.items()}

100%|██████████| 13/13 [00:06<00:00,  1.98it/s]

In [68]:
df=pd.DataFrame(data)
df.columns=genre_kor_list
df

,에피소드,옴니버스,스토리,일상,개그,판타지,액션,드라마,순정,감성,스릴러,무협/사극,스포츠
0,대학원 탈출일지/요다/9.97,먹는 인생/홍끼/9.96,99강화나무몽둥이/홍실 / 지페리/9.78,대학원 탈출일지/요다/9.97,마루는 강쥐/모죠/9.98,99강화나무몽둥이/홍실 / 지페리/9.78,김부장/박태준 만화회사 .../9.24,외모지상주의/박태준/9.47,내 남편과 결혼해줘/LICO / 성소작/9.95,웅크/나유진/9.97,퍼니게임/배진수/9.82,나노마신/현절무 / 금강불.../9.92,윈드브레이커/조용석/9.83
1,마루는 강쥐/모죠/9.98,조조코믹스/이동건/9.97,김부장/박태준 만화회사 .../9.24,먹는 인생/홍끼/9.96,나쁜사람/둠스/9.68,전지적 독자 시점/UMI / 슬리피.../9.95,참교육/채용택 / 한가람/9.86,뷰티풀 군바리/설이 / 윤성원/9.81,여신강림/야옹이/9.38,6월의 라벤더/밤희 / 게살/9.94,"사형소년/박태준만화회사, .../9.90",광마회귀/JP / 이히 /.../9.97,격기3반/이학/9.53
2,2022 몰래보는 로맨스/웹툰작가/9.85,언다잉/임목원/9.87,내 남편과 결혼해줘/LICO / 성소작/9.95,독립일기/자까/9.97,이십팔세기 광팬/컷부/9.90,호랑이형님/이상규/9.95,싸움독학/박태준 만화회사 .../9.72,연애혁명/232/9.86,2022 몰래보는 로맨스/웹툰작가/9.85,슈퍼스타 천대리/박경원 / 이재국.../9.80,악몽의 형상/김용키/9.92,장씨세가 호위무사/김인호 / 조형근/9.93,빌드업/911/9.83
3,약한영웅/서패스 / 김진석/9.82,소름일기/siAm/9.87,참교육/채용택 / 한가람/9.86,"안녕, 나의 수집/하린/9.95",여자를 사귀고 싶다/노갓량 / 영오/9.23,갓 오브 하이스쿨/박용제/9.64,헬퍼 2 : 킬베로스/삭/8.78,퀘스트지상주의/박태준 만화회사/9.80,어쩌다보니 천생연분/꿀타래 / 담초/9.97,연우의 순정/이솔/9.98,똑 닮은 딸/이담/9.98,천마육성/광휘 / 조형근/9.88,가비지타임/2사장/9.96
4,비즈니스 여친/루즌아 / 서해/9.74,기묘한 만화/몬킬/9.57,외모지상주의/박태준/9.47,윌유메리미/마인드C/9.92,죄송한데 주인공이세요?/조석/9.95,내가 키운 S급들/seri / 비완.../9.93,입학용병/YC / 락현/9.89,팔이피플/매미 / 희세/9.94,1을 줄게/김계란/9.96,밥 먹고 갈래요?/오묘/9.97,언다잉/임목원/9.87,무림서부/웨스트 / 정한길.../9.89,빅맨/하하영/9.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1699,NaN,NaN,흥부놀부전/황동/9.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1700,NaN,NaN,대디고라운드/희나리/8.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1701,NaN,NaN,102030/H / JMS/8.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1702,NaN,NaN,레이디악숀/령 / 박혬/9.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1703,NaN,NaN,파우스트 인 러브/허니맨 / 손팡/9.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm

In [38]:
url='https://finance.naver.com/sise/sise_index_day.naver?code=KPI200&page=1'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')

In [72]:
url='https://finance.naver.com/sise/sise_index_day.naver?code=KPI200&page=1'
resp=requests.get(url)
soup=BeautifulSoup(resp.content, 'lxml')

columns_tags=soup.select('table.type_1 tr th') # 항목

# 맨 뒤 페이지 가져오기
last_pg=soup.select('td.pgRR a')[0]['href'].split('page=')[-1]

df_list=[]

for pg in tqdm(range(1,int(last_pg)+1)):
    url='https://finance.naver.com/sise/sise_index_day.naver?code=KPI200&page={}'.format(pg)
    resp=requests.get(url)
    soup=BeautifulSoup(resp.content, 'lxml')

    dic={} # 
    for i in columns_tags:
        dic[f'{i.text}']=[]

    date_tags=soup.select('td.date') # 날짜
    price_tags=soup.select('td.number_1')[::4] # 체결가
    rate_per_tags=soup.select('td.number_1')[1::4] # 등락률 strip()필요
    vol_tags=soup.select('td.number_1')[2::4] # 거래량
    price_vol_tags=soup.select('td.number_1')[3::4] # 거래대금
    rate_day_tags=soup.select('td.rate_down span.tah.p11') # 전일비

    for_range=min(len(date_tags), len(price_tags), len(rate_per_tags), len(vol_tags), len(price_vol_tags), len(rate_day_tags))

    for i in range(for_range):
        if rate_day_tags[i]['class'][-1]=='nv01':
            dic['전일비'].append("-"+rate_day_tags[i].text.strip())
        else:
            dic['전일비'].append(rate_day_tags[i].text.strip())
        dic['날짜'].append(date_tags[i].text)
        dic['체결가'].append(price_tags[i].text)
        dic['등락률'].append(rate_per_tags[i].text.strip())
        dic['거래량(천주)'].append(vol_tags[i].text)
        dic['거래대금(백만)'].append(rate_day_tags[i].text.strip())

    df=pd.DataFrame(dic)
    df_list.append(df)

100%|██████████| 693/693 [03:31<00:00,  3.27it/s]

In [73]:
total_df=pd.concat(df_list, ignore_index=True)
total_df

              날짜     체결가    전일비     등락률  거래량(천주) 거래대금(백만)
0     2022.10.31  297.72   2.66  +0.90%   45,415     2.66
1     2022.10.28  295.06  -3.76  -1.26%  131,077     3.76
2     2022.10.27  298.82   4.97  +1.69%  176,203     4.97
3     2022.10.26  293.85   2.27  +0.78%  122,301     2.27
4     2022.10.25  291.58   0.11  +0.04%  116,351     0.11
...          ...     ...    ...     ...      ...      ...
4153  2006.01.09  180.30  -0.57  -0.32%  191,222     0.57
4154  2006.01.06  180.87   2.05  +1.15%  206,313     2.05
4155  2006.01.05  178.82  -1.09  -0.61%  206,332     1.09
4156  2006.01.04  179.91   1.10  +0.62%  188,841     1.10
4157  2006.01.03  178.81   0.52  +0.29%  158,041     0.52

[4158 rows x 6 columns]